spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database_Users_2.3.1
    username: postgres
    password: postgre
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
